Parameters:
  instance_charge_type:
    Type: String
    AssociationProperty: ChargeType
    AssociationPropertyMetadata:
      LocaleKey: InstanceChargeType
    Default: PostPaid
    Label:
      zh-cn: 付费类型
      en: ECS Instance Billing Method
    AllowedValues:
      - PostPaid
      - PrePaid
  period_unit:
    Type: String
    AssociationProperty: PayPeriodUnit
    AssociationPropertyMetadata:
      Visible:
        Condition:
          Fn::Not:
            Fn::Equals:
              - ${instance_charge_type}
              - PostPaid
    Default: Month
    AllowedValues:
      - Month
    Label:
      zh-cn: 购买资源时长周期
      en: Purchase Cycle
  period:
    Type: Number
    AssociationProperty: PayPeriod
    AssociationPropertyMetadata:
      Visible:
        Condition:
          Fn::Not:
            Fn::Equals:
              - ${instance_charge_type}
              - PostPaid
    Default: 1
    Label:
      zh-cn: 购买资源时长
      en: Purchase Duration
    AllowedValues:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 12
      - 24
      - 36
      - 48
  instance_type:
    Type: String
    AssociationProperty: ALIYUN::ECS::Instance::InstanceType
    AssociationPropertyMetadata:
      InstanceChargeType: ${instance_charge_type}
      Constraints:
        InstanceTypeFamily:
          - ecs.u1
          - ecs.e
    Label:
      zh-cn: 实例规格
      en: The instance tye of ECS instance
  password:
    Type: String
    Label:
      en: Instance Password
      zh-cn: 实例密码
    Description:
      en: Server login password, Length 8-30, must contain three(Capital letters, lowercase letters, numbers, ()`~!@#$%^&*_-+=|{}[]:;'<>,.?/ Special symbol in).
      zh-cn: 服务器登录密码,长度8-30，必须包含三项（大写字母、小写字母、数字、 ()`~!@#$%^&*_-+=|{}[]:;'<>,.?/ 中的特殊符号）。
    NoEcho: true
    AssociationProperty: ALIYUN::ECS::Instance::Password
    ConstraintDescription:
      en: '8-32 characters, can contain size letters, Numbers and special symbols, including:! @ # $ % ^ & * ( ) _ + - ='
      zh-cn: 8-32个字符,可包含大小字母、数字及特殊符号（包含：!@#$%^&*()_+-=）
    MinLength: 8
    MaxLength: 32
  zone_id:
    Type: String
    AssociationProperty: ALIYUN::ECS::Instance::ZoneId
    Label:
      zh-cn: 可用区
      en: The ZoneId used to launch service
  vpc_cidr:
    Type: String
    Label:
      en: VPC CIDR IPv4 Block
      zh-cn: 专有网络IPv4网段
    Description:
      zh-cn: VPC的ip地址段范围，<br>您可以使用以下的ip地址段或其子网:<br><font color='green'>[10.0.0.0/8]</font><br><font color='green'>[172.16.0.0/12]</font><br><font color='green'>[192.168.0.0/16]</font>
      en: 'The ip address range of the VPC in the CidrBlock form; <br>You can use the following ip address ranges and their subnets: <br><font color=''green''>[10.0.0.0/8]</font><br><font color=''green''>[172.16.0.0/12]</font><br><font color=''green''>[192.168.0.0/16]</font>'
    Default: 192.168.0.0/16
    AssociationProperty: ALIYUN::VPC::VPC::CidrBlock
  vswitch_cidrs:
    Type: String
    Label:
      en: VSwitch CIDR Block
      zh-cn: 交换机子网网段
    Description:
      zh-cn: 必须属于VPC的子网段。
      en: Must belong to the subnet segment of VPC.
    Default: 192.168.0.0/24
    Required: true
    AssociationProperty: ALIYUN::VPC::VSwitch::CidrBlock
Metadata:
  ALIYUN::ROS::Interface:
    ParameterGroups:
      - Parameters:
          - instance_charge_type
          - period_unit
          - period
        Label:
          default: 付费类型配置
      - Parameters:
          - instance_type
          - password
        Label:
          default: 资源配置
      - Parameters:
          - zone_id
          - vpc_cidr
          - vswitch_cidrs
        Label:
          default: 可用区配置
Outputs:
  server_address:
    Description:
      zh-cn: 访问地址
      en: ServerAddress